SVCINT-1058 update slack result template visual
coveo/search-ui pull request #1910
Opened 2022-10-26 14:21 UTC by jbvouma

[SVCINT-1058](https://coveord.atlassian.net/browse/SVCINT-1058)

Some update in the Slack JSUI result template to match the changes asked here.

Final result
![image](https://user-images.githubusercontent.com/67848363/198051213-dda83b41-ef42-43a0-9544-4824ebe83f64.png)

[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)

2022-10-26 14:40 UTC, mikegron requested changes

2022-10-26 14:40 UTC, mikegron commented
Vraiment nice !!

2022-10-26 15:17 UTC, jbvouma commented on src/ui/Templates/CoreHelpers.ts
> +TemplateHelpers.registerTemplateHelper('pluralReplyHelper', (count: number) => (count == 1 ? 'reply' : 'replies'));
Done!

2022-10-26 16:58 UTC, pathiery approved these changes
Looks good ! Did you test to make sure the folding results ? Not sure what that comment is about ....

2022-10-26 18:13 UTC, jbvouma commented
> Looks good ! Did you test to make sure the folding results ? Not sure what that comment is about ....

I just checked it, the [data-range](https://coveo.github.io/search-ui/classes/foldingforthread.html#options.range) set to 0 should do the trick.

2022-10-26 21:21 UTC, mikegron approved these changes

2022-10-27 12:46 UTC, dguerinCoveo approved these changes
Do you know why there was a different behaviour in dev and prod before you began?

2022-10-27 12:59 UTC, jbvouma commented
> Do you know why there was a different behaviour in dev and prod before you began?

Not really but I was testing in the `coveo internal testing` org and let Denis know about it.

2022-10-27 13:10 UTC, btaillon approved these changes

2022-10-27 13:18 UTC, merged